name: trigger-rally-ogra
base: core18
adopt-info: trigger-rally
summary: 3D rally simulation with a great physics engine
description: |
  A 3D rally simulation with a great physics engine for drifting,
  over 200 maps, different terrain materials like dirt, asphalt, sand,
  ice etc. and various weather, light and fog conditions give this
  rally simulation the edge over many other free games. You need to
  make it through the maps in often tight time limits and can further
  improve by beating the recorded high scores. All attached single
  races must be finished in time in order to win an event, unlocking
  additional events and cars. Most maps are equipped with spoken
  co-driver notes and co-driver icons.

grade: stable
confinement: strict

apps:
  trigger-rally-ogra:
    command: desktop-launch $SNAP/usr/games/trigger-rally
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/pulseaudio
    plugs:
      - audio-playback
      - desktop
      - home
      - joystick
      - network
      - network-bind
      - opengl
      - unity7
      - x11

layout:
  /etc/openal/alsoft.conf:
    bind-file: $SNAP/etc/openal/alsoft.conf

parts:
  tinyxml2:
    source: https://github.com/leethomason/tinyxml2.git
    plugin: cmake
  trigger-rally:
    source: https://svn.code.sf.net/p/trigger-rally/code
    source-type: svn
    plugin: make
    after: [ tinyxml2 ]
    override-build: |
      export DESTDIR=$SNAPCRAFT_PART_INSTALL
      export prefix=/usr
      export OPTIMS='-march=x86-64 -mtune=generic -O2'
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      cd src
      make
      make install
      sed "s/\/usr/\/snap\/$SNAPCRAFT_PROJECT_NAME\/current\/usr/g" -i \
           $SNAPCRAFT_PART_INSTALL/usr/games/trigger-rally.config.defs
      # set version
      COMMIT="$(svn log|grep -v ^- 2>/dev/null|head -1|sed 's/ |.*$//')"
      snapcraftctl set-version "$(grep ^DISTVER GNUmakefile|sed 's/^.*= //')-${COMMIT}"
    build-packages:
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libglew-dev
      - libopenal-dev
      - libalut-dev
      - libphysfs-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - subversion
    stage-packages:
      - libalut0
      - libasound2
      - libasyncns0
      - libflac8
      - libgl1
      - libglew2.0
      - libglu1-mesa
      - libglvnd0
      - libglx0
      - libjbig0
      - libjpeg-turbo8
      - libmirclient9
      - libogg0
      - libopenal1
      - libphysfs1
      - libpng16-16
      - libpulse0
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsndfile1
      - libsndio6.1
      - libtiff5
      - libvorbis0a
      - libvorbisenc2
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwebp6
      - libx11-6
      - libxau6
      - libxcb1
      - libxcursor1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxrender1
      - libxss1
      - libxxf86vm1
  glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    override-prime: |
      snapcraftctl prime
      # fix nvidia driver handling
      sed 's;^export LIBGL_DRIVERS_PATH.*;if \[ -e "/var/lib/snapd/lib/gl/xorg/nvidia_drv.so" \]\; then\n  export LIBGL_DRIVERS_PATH=/var/lib/snapd/lib/gl/xorg\n  export LD_LIBRARY_PATH=/var/lib/snapd/lib/gl:$LD_LIBRARY_PATH\nelse\n  export LIBGL_DRIVERS_PATH=$SNAP/usr/lib/$ARCH/dri\nfi;' -i bin/desktop-launch
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
